<?php
/**
 * dashboard.boutimar.com — password gate for the orchestration dashboard.
 *
 * Architecture credit: Albaloo Studio — albaloostudio.com
 * Owner: Alireza Mozaffari
 *
 * WHY PHP AND NOT .htaccess
 * -------------------------
 * Netafraz serves static files through nginx directly, which is why Header and
 * Expires rules on this host only ever reached PHP and never static HTML. The
 * same mechanism means a .htaccess basic-auth block would NOT protect a static
 * dashboard.html — the page would look gated and be readable by anyone with the
 * URL. PHP is interpreted, so this is the one layer on this stack that actually
 * enforces something.
 *
 * WHERE THE DATA LIVES
 * --------------------
 * ../private/dashboard.html — OUTSIDE the web root, so nginx cannot serve it
 * even if someone guesses the name. This file reads it and prints it after the
 * session check. If the private directory is unreachable because the FTP
 * account is chrooted to public_html, see SETUP-DASHBOARD.md: the fallback is a
 * random filename, which is weaker and is documented as such.
 *
 * WHAT IT NEVER DOES
 * ------------------
 * Store or log the password. Only a bcrypt hash is deployed, generated by
 * Alireza and held in GitHub's secret store; the plaintext exists on his
 * machine and nowhere else.
 */

declare(strict_types=1);

const DATA_FILE = __DIR__ . '/../private/dashboard.html';
const AUTH_FILE = __DIR__ . '/../private/dashboard-auth.php';
const SESSION_HOURS = 12;

// Never indexed, never cached by a shared proxy. Set before any output, and
// set here rather than in .htaccess for the reason in the header comment.
header('X-Robots-Tag: noindex, nofollow, noarchive');
header('Referrer-Policy: no-referrer');
header('Cache-Control: no-store, private');
header('X-Content-Type-Options: nosniff');

session_set_cookie_params([
    'lifetime' => SESSION_HOURS * 3600,
    'path'     => '/',
    'secure'   => !empty($_SERVER['HTTPS']),
    'httponly' => true,
    'samesite' => 'Strict',
]);
session_start();

/** The bcrypt hash, deployed separately and never in the repository. */
function stored_hash(): ?string {
    if (!is_readable(AUTH_FILE)) return null;
    $h = require AUTH_FILE;
    return (is_string($h) && $h !== '') ? $h : null;
}

function fail(string $msg, int $code = 200): void {
    http_response_code($code);
    render_login($msg);
    exit;
}

function render_login(string $msg = ''): void {
    $m = $msg === '' ? '' : '<p class="err">' . htmlspecialchars($msg, ENT_QUOTES) . '</p>';
    echo <<<HTML
<!doctype html><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="robots" content="noindex,nofollow">
<title>Albaloo orchestration</title>
<style>
:root{--bg:#0d1b1e;--panel:#12262b;--line:#1e3a41;--ink:#e8f1f2;--dim:#8fa9ae;--accent:#5ec5c7;--bad:#d1615d}
*{box-sizing:border-box}
body{margin:0;min-height:100vh;display:grid;place-items:center;background:var(--bg);color:var(--ink);
font:15px/1.5 ui-sans-serif,system-ui,-apple-system,"Segoe UI",Roboto,sans-serif}
form{background:var(--panel);border:1px solid var(--line);border-radius:12px;padding:26px 24px;width:min(340px,92vw)}
h1{font-size:17px;margin:0 0 4px;letter-spacing:-.01em}
p.sub{color:var(--dim);font-size:13px;margin:0 0 18px}
input{width:100%;padding:11px 12px;border-radius:8px;border:1px solid var(--line);
background:#0b171a;color:var(--ink);font-size:15px}
button{width:100%;margin-top:12px;padding:11px;border:0;border-radius:8px;cursor:pointer;
background:var(--accent);color:#06232a;font-weight:650;font-size:15px}
.err{color:var(--bad);font-size:13px;margin:0 0 12px}
</style>
<form method="post" autocomplete="off">
<h1>Albaloo orchestration</h1>
<p class="sub">Internal. Competitor research, cost and unreviewed drafts.</p>
{$m}<input type="password" name="p" placeholder="Password" autofocus required>
<button type="submit">Open</button>
</form>
HTML;
}

// ── the gate ────────────────────────────────────────────────────────────────
if (isset($_GET['logout'])) {
    $_SESSION = [];
    session_destroy();
    header('Location: ' . strtok($_SERVER['REQUEST_URI'], '?'));
    exit;
}

$hash = stored_hash();
if ($hash === null) {
    // Deliberately explicit: a missing hash must never silently mean "open".
    fail('Not configured yet — the password hash has not been deployed.', 503);
}

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    // A fixed delay on every attempt, right or wrong. Cheap, and it removes
    // both timing signal and the value of scripting the form.
    usleep(400000);
    if (password_verify((string)($_POST['p'] ?? ''), $hash)) {
        session_regenerate_id(true);           // no fixation on a shared password
        $_SESSION['ok'] = true;
        $_SESSION['at'] = time();
        header('Location: ' . strtok($_SERVER['REQUEST_URI'], '?'));
        exit;
    }
    fail('Wrong password.');
}

$fresh = ($_SESSION['ok'] ?? false) && (time() - (int)($_SESSION['at'] ?? 0)) < SESSION_HOURS * 3600;
if (!$fresh) {
    if ($_SESSION) { $_SESSION = []; session_destroy(); }
    render_login();
    exit;
}

// ── authenticated ───────────────────────────────────────────────────────────
if (!is_readable(DATA_FILE)) {
    http_response_code(503);
    echo '<!doctype html><meta charset="utf-8"><p style="font-family:system-ui;padding:2rem">'
       . 'The dashboard has not been built yet. The Monday workflow writes it; '
       . 'run <em>Portfolio dashboard</em> manually to fill this in.</p>';
    exit;
}
header('Content-Type: text/html; charset=utf-8');
readfile(DATA_FILE);
echo '<p style="text-align:center;padding:18px;font:13px system-ui;color:#8fa9ae">'
   . '<a href="?logout=1" style="color:#5ec5c7">Sign out</a></p>';
